# Generated by Django 3.0 on 2021-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='quantity',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineinfo',
            name='remaining_tablets',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='required_tablets',
            field=models.IntegerField(max_length=20),
        ),
    ]
