# Generated by Django 3.0 on 2021-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210619_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicineinfo',
            name='remaining_tablets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='required_tablets',
            field=models.IntegerField(),
        ),
    ]
